import 'package:flutter/material.dart';

import 'package:flutter_app/pages/component_15_variant_2.dart';


void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter App',
      home: Scaffold(

        body: Component15Variant2(),
        // body: Component15Variant21(),
        // body: Component16(),
        // body: Component17(),
        // body: Component18(),
        // body: Component26(),
        // body: Component27(),
        // body: Component28(),
        // body: Component29(),
        // body: Component31(),
        // body: Component34(),
        // body: Component35(),
        // body: Component36(),
        // body: Component37(),
        // body: Component38(),
        // body: Component39(),
        // body: Component42(),
        // body: Component43(),
        // body: Component52(),
        // body: Component73(),
        // body: Component74(),
        // body: Component80(),
        // body: Component84(),
        // body: DontHaveAnAccountSignUp(),
        // body: ForgotPassword(),
        // body: Frame34927(),
        // body: Group37214(),
        // body: Group37222(),
        // body: Group37232(),
        // body: Group37234(),
        // body: Group37235(),
        // body: Group37240(),
        // body: Group953(),
        // body: HomeIndicator(),
        // body: Icon(),
        // body: LoginScreen(),
        // body: LoginScreenPopup1(),
        // body: LoginScreenPopup2(),
        // body: OtpScreen(),
        // body: Property1Default(),
        // body: Property1Default1(),
        // body: Property1Variant2(),
        // body: SeivarStartupScreen(),
        // body: SetPasswordScreen(),
        // body: SignupScreen(),
        // body: StatusBar(),
        // body: TamilUserChatAssistantScreen(),
        // body: TamilUserChatAssistantScreen1(),
        // body: TamilUserChatAssistantSidebarScreen(),
        // body: TamilUserHelpCentreScreen(),
        // body: TamilUserHomeScreen(),
        // body: TamilUserProfileLogoutScreen(),
        // body: TamilUserProfilePopupScreen(),
        // body: TamilUserProfileScreen(),
        // body: TamilUserProfileScreen1(),
        // body: TamilUserProfileScreen2(),
        // body: TamilUserProfileScreen3(),
        // body: TamilUserProfileScreen4(),
        // body: TamilUserProfileScreen5(),
        // body: TamilUserProfileScreen6(),
        // body: TamilUserProfileScreen7(),
        // body: TamilWorkSelect1(),
        // body: TamilWorkSelect2(),
        // body: TamilWorkSelect3(),
        // body: TamilWorkerHelpCentreScreen(),
        // body: TamilWorkerHomeScreen1(),
        // body: TamilWorkerHomeScreen2(),
        // body: TamilWorkerHomeScreen3(),
        // body: TamilWorkerProfileScreen(),
        // body: TamilWorkerProfileScreen1(),
        // body: TamilWorkerProfileScreen2(),
        // body: TamilWorkerTravelScreen(),
        // body: TamilWorkersBookingsPendingScreen(),
        // body: UserBookingScreen(),
        // body: UserBookingsScreen(),
        // body: UserCardScreen(),
        // body: UserChatAssistantScreen(),
        // body: UserChatAssistantScreenConvo(),
        // body: UserChatAssistantSidebarScreen(),
        // body: UserGpayScreen(),
        // body: UserHelpCentreScreen(),
        // body: UserHomeScreen(),
        // body: UserPaymentConfirmationScreen(),
        // body: UserPaymentScreen1(),
        // body: UserPaymentScreen2(),
        // body: UserProfileLogoutScreen(),
        // body: UserProfilePopupScreen(),
        // body: UserProfilePopupScreen1(),
        // body: UserProfileScreen(),
        // body: WorkSelect1(),
        // body: WorkSelect2(),
        // body: WorkSelect3(),
        // body: WorkerHomeScreen1(),
        // body: WorkerHomeScreen2(),
        // body: WorkerHomeScreen3(),
        // body: WorkerProfileLogoutScreen(),
        // body: WorkerProfileScreen1(),
        // body: WorkerProfileScreen2(),
        // body: WorkerProfileScreen3(),
        // body: WorkerRegisterScreen(),
        // body: WorkerTravelScreen(),
        // body: WorkererHelpCentreScreen(),
        // body: WorkersBookingsPendingScreen(),

      ),
    );
  }
}
